apiVersion: apps/v1 
kind: Deployment
metadata:
  name: laravel-deploy
  namespace: laravel
spec:
  selector:  
    matchLabels:
      app: laravel
  replicas: 1
  strategy:
     type: Recreate
  template:   
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        #image: nginx:latest
        ports:
        - containerPort: 8000
        image: bitnami/laravel:latest
        env:
          - name: LARAVEL_DATABASE_HOST
            value: mariadb-service
          - name: LARAVEL_DATABASE_PORT_NUMBER
            value: "3306"
          - name: LARAVEL_DATABASE_USER
            value: bn_myapp
          - name: LARAVEL_DATABASE_NAME
            value: bitnami_myapp


