apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-postgres
  namespace: laravel
  labels:
    app: postgres
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres163
          image: postgres:16.3
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: datos-postgres-env
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: datos-postgres-env
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: datos-postgres-env
                  key: POSTGRES_DB

