apiVersion: apps/v1 
kind: Deployment
metadata:
  name: phpmyadmin-deploy
  namespace: phpmyadmin
spec:
  selector:  
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:  
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:5.2.1
        ports:
        - containerPort: 80
        env:
          - name: PMA_HOST
            valueFrom:
              configMapKeyRef:
                name: datos-phpmyadmin
                key: DB_DATABASE_HOST
          - name: PMA_PORT
            valueFrom:
              configMapKeyRef:
                name: datos-phpmyadmin
                key: DB_DATABASE_PORT_NUMBER
          - name: PMA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: phpmyadmin-credentials
                key: DB_DATABASE_PASSWORD
          - name: PMA_USER
            valueFrom:
              configMapKeyRef:
                name: datos-phpmyadmin
                key: DB_DATABASE_USER
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: phpmyadmin-credentials
                key: DB_ROOT_PASSWORD
